### ISSUE TITLE
Support the driver returning JObject instead of string for Jsonb

### ISSUE THREAD

**Issue by oyzar** [akkadotnet/Akka.Persistence.PostgreSql#266]
**Version Information**
Version of Akka.NET? 1.15.20
Which Akka.NET Modules? Akka.Persistence.PostgreSql

**Describe the bug**
If the extensionmethod UseJsonNet from Npgsql.Json.NET 8.0.3 is called. The driver returns JsonB as JObject instead of string. This fails inside the deserialization inside of akka if that is the case.

**To Reproduce**

_Links to working reproductions on Github / Gitlab are very much appreciated_

**Expected behavior**

**Actual behavior**
What actually happened and how did it differ from your expectations?

**Screenshots**

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?

**Additional context**

**Comment by Arkatufus** [comment]
It turns out that the underlying issue was caused by a breaking change between `Npgsql` v8 and `Npgsql.Json.NET`.

Making the change outlined inside #267 is risky as it changes the behavior of the plugin for all users and making this backward compatible requires more engineering work that we could not spare at this moment, as the plugin itself is nearing its end of life.

Please consider switching to `Akka.Persistence.Sql` and changing your storage type to `ByteA`.
